# Generated by Django 5.1.2 on 2024-11-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('ruc_empresa', models.CharField(max_length=200, unique=True)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mes', models.IntegerField(default=1)),
                ('nombre_mes', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha_registro')),
            ],
            options={
                'db_table': 'Meses',
            },
        ),
        migrations.CreateModel(
            name='SesionesActivas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('fecha_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('token_session', models.CharField(blank=True, max_length=100)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'SesionesActivas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=200)),
                ('apellido_usuario', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('ruc', models.IntegerField()),
                ('div', models.IntegerField()),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200)),
                ('ultima_conexion', models.DateTimeField(verbose_name='fecha ultma conexion')),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=200)),
                ('fecha_factura', models.DateTimeField(verbose_name='fecha factura')),
                ('total_factura', models.IntegerField()),
                ('iva10', models.IntegerField()),
                ('iva5', models.IntegerField()),
                ('liquidacion_iva', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyTaxesBackendApp.empresas')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyTaxesBackendApp.usuarios')),
            ],
            options={
                'db_table': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='FacturasDetalle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha registro')),
                ('factura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyTaxesBackendApp.facturas')),
            ],
            options={
                'db_table': 'FacturasDetalle',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_recuperacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha creacion')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='fecha vencimiento')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha vencimiento')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyTaxesBackendApp.usuarios')),
            ],
            options={
                'db_table': 'SolicitudPassword',
            },
        ),
    ]
