# Generated by Django 5.1.2 on 2024-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0002_facturas_cdc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturasdetalle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
