# Generated by Django 5.1.2 on 2025-01-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0004_facturas_tipo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasdetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='MyTaxesBackendApp.facturas'),
        ),
        migrations.AlterField(
            model_name='facturasdetalle',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
