# Generated by Django 5.1.2 on 2025-02-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0005_alter_facturasdetalle_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('link_descarga', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha creacion')),
            ],
            options={
                'db_table': 'Versiones',
            },
        ),
    ]
