# Generated by Django 5.1.2 on 2025-02-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0007_sesionesactivas_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
