# Generated by Django 5.1.2 on 2025-02-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0008_usuarios_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionesactivas',
            name='version',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='version',
        ),
    ]
