# Generated by Django 5.1.2 on 2025-02-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTaxesBackendApp', '0009_remove_sesionesactivas_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpassword',
            name='codigo_tipo',
            field=models.IntegerField(choices=[(1, 'Cambio de contraseña'), (2, 'Recuperación de contraseña')], default=2),
        ),
    ]
